Added docs workflow

diff --git a/lvs/action.yaml b/lvs/action.yaml
--- a/lvs/action.yaml
+++ b/lvs/action.yaml
@@ -28,6 +28,24 @@ runs:
         shell: bash
         run: |
           python3 ${GITHUB_ACTION_PATH}/../yamlToVariables info.yaml --paths "library,cell" >> "$GITHUB_OUTPUT"
+      - name: Check for Cell
+        shell: bash
+        env:
+          CELL: ${{ steps.info.outputs.cell }}
+          LIBRARY: ${{ steps.info.outputs.library }}
+        run: |
+          export CSCH=../design/${LIBRARY}/${CELL}.sch
+          export CMAG=../design/${LIBRARY}/${CELL}.mag
+
+          if [[ -f ${CSCH}]]; then
+            echo "::error:: Could not find Schematic ${CSCH}"
+            exit 1
+          fi
+
+          if [[ -f ${CMAG} ]]; then
+            echo "::error:: Could not find Layout ${CMAG}"
+            exit 1
+          fi
       - name: Run LVS
         shell: bash
         env:
@@ -38,10 +56,6 @@ runs:
           echo "$HOME/.local/bin" >> $GITHUB_PATH
           echo "/opt/eda/bin" >> $GITHUB_PATH
           cd work
-          #export CSCH=../design/${LIBRARY}/${CELL}.sch
-          #export CMAG=../design/${LIBRARY}/${CELL}.mag
-          #test -f ${CSCH} || echo "::error:: Could not find Schematic ${CSCH}" && exit 1
-          #test -f ${CMAG} || echo "::error:: Could not find Layout ${CMAG}" && exit 1
           make xlvs CELL=$CELL LIB=$LIBRARY
           echo -e "\n\n# LPE\n\n" >> $GITHUB_STEP_SUMMARY
           echo -e "\`\`\`bash\n" >> $GITHUB_STEP_SUMMARY
