Added docs workflow

diff --git a/drc/action.yaml b/drc/action.yaml
--- a/drc/action.yaml
+++ b/drc/action.yaml
@@ -24,7 +24,8 @@ runs:
           echo "$HOME/.local/bin" >> $GITHUB_PATH
           echo "/opt/eda/bin" >> $GITHUB_PATH
           cd work
-          export
+          export CMAG=../design/${LIBRARY}/${CELL}.mag
+          test -f ${CMAG} || echo "::error:: Could not find Layout ${CMAG}" && exit 1
           make drc CELL=$CELL LIB=$LIBRARY
           cat drc/${CELL}_drc.log >> $GITHUB_STEP_SUMMARY
           tail -n 1 drc/${CELL}_drc.log| perl -ne '$exit =0;if(!m/:\s+0\n/ig){$exit = 1;}if(m/couldn?t be read/ig){$exit = 2}; exit $exit'
diff --git a/lvs/action.yaml b/lvs/action.yaml
--- a/lvs/action.yaml
+++ b/lvs/action.yaml
@@ -38,6 +38,10 @@ runs:
           echo "$HOME/.local/bin" >> $GITHUB_PATH
           echo "/opt/eda/bin" >> $GITHUB_PATH
           cd work
+          export CSCH=../design/${LIBRARY}/${CELL}.sch
+          export CMAG=../design/${LIBRARY}/${CELL}.mag
+          test -f ${CSCH} || echo "::error:: Could not find Schematic ${CSCH}" && exit 1
+          test -f ${CMAG} || echo "::error:: Could not find Layout ${CMAG}" && exit 1
           make xlvs CELL=$CELL LIB=$LIBRARY
           echo -e "\n\n# LPE\n\n" >> $GITHUB_STEP_SUMMARY
           echo -e "\`\`\`bash\n" >> $GITHUB_STEP_SUMMARY
