Added info

diff --git a/gds/action.yaml b/gds/action.yaml
--- a/gds/action.yaml
+++ b/gds/action.yaml
@@ -33,8 +33,11 @@ runs:
           echo "$HOME/.local/bin" >> $GITHUB_PATH
           echo "/opt/eda/bin" >> $GITHUB_PATH
           cd work
-          test -f ../design/${LIBRARY}/${CELL}.sch || exit 1
-          test -f ../design/${LIBRARY}/${CELL}.mag || exit 1
+          export CSCH=../design/${LIBRARY}/${CELL}.sch
+          export CMAG=../design/${LIBRARY}/${CELL}.mag
+          test -f ${CSCH} || echo "::error Could not find Schematic ${CSCH}" && exit 1
+          test -f ${CMAG} || echo "::error Could not find Layout ${CMAG}" && exit 1
+
           make gds CELL=$CELL LIB=$LIBRARY
           ls -l gds
           cat gds/${CELL}.log >> $GITHUB_STEP_SUMMARY
